#!/usr/bin/env bash
# run_ex5_python.sh
# Convenience launcher for the ex5 Python min/max/avg example (writer + reader) plus server.
#
# Features:
#  - Generates dataspaces.conf if absent.
#  - Verifies dims matches ARRAY_SIZE.
#  - Launches server, then writer & reader MPI jobs.
#  - Streams output to separate log files & console.
#  - Cleans up on Ctrl-C.
#
# Requirements:
#  - mpirun/mpicc available (load your MPI module / spack load mpi).
#  - mochi-margo, lz4, etc. loaded before building.
#  - Build completed with -DDSPACES_PYTHON_BINDINGS=ON.
#
# Usage examples:
#   scripts/run_ex5_python.sh               # defaults
#   scripts/run_ex5_python.sh -w 8 -r 8 -a 1024 -t sockets
#   scripts/run_ex5_python.sh --server 2 --writer 4 --reader 4 --array 2048 --transport ofi+verbs
#   scripts/run_ex5_python.sh --debug
#
# Options:
#   -s|--server <N>     Server MPI ranks (default 1)
#   -w|--writer <N>     Writer MPI ranks (default 4)
#   -r|--reader <N>     Reader MPI ranks (default 4)
#   -a|--array  <N>     Global 1D array size (default 128)
#   -t|--transport STR  Mercury/Margo transport (default sockets)
#   -b|--build DIR      Build directory (default ./build)
#   -e|--example DIR    Example dir (default examples/ex5_minmax_python)
#   -d|--debug          Enable DSPACES_DEBUG=1
#   --shared-libs       Add build lib dir to LD_LIBRARY_PATH (if built shared)
#   -h|--help           Show help
#   --no-tail           Do not live-tail logs (print at end instead)
#
# The script expects num_apps=2 (writer + reader) in dataspaces.conf.

set -euo pipefail

SERVER_RANKS=1
WRITER_RANKS=4
READER_RANKS=4
ARRAY_SIZE=128
TRANSPORT="sockets"
BUILD_DIR="build"
EXAMPLE_DIR="examples/ex5_minmax_python"
ENABLE_DEBUG=0
USE_SHARED_LIBS=0
NO_TAIL=0

print_help() {
  grep '^# ' "$0" | sed 's/^# \{0,1\}//'
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    -s|--server) SERVER_RANKS=$2; shift 2;;
    -w|--writer) WRITER_RANKS=$2; shift 2;;
    -r|--reader) READER_RANKS=$2; shift 2;;
    -a|--array) ARRAY_SIZE=$2; shift 2;;
    -t|--transport) TRANSPORT=$2; shift 2;;
    -b|--build) BUILD_DIR=$2; shift 2;;
    -e|--example) EXAMPLE_DIR=$2; shift 2;;
    -d|--debug) ENABLE_DEBUG=1; shift;;
    --shared-libs) USE_SHARED_LIBS=1; shift;;
  -h|--help) print_help; exit 0;;
  --no-tail) NO_TAIL=1; shift;;
    *) echo "Unknown option: $1" >&2; print_help; exit 1;;
  esac
done

ROOT_DIR=$(cd "$(dirname "$0")/.." && pwd)
EX_DIR="$ROOT_DIR/$EXAMPLE_DIR"
BDIR="$ROOT_DIR/$BUILD_DIR"

if [[ ! -d "$EX_DIR" ]]; then
  echo "[ERROR] Example directory not found: $EX_DIR" >&2
  exit 1
fi
if [[ ! -d "$BDIR" ]]; then
  echo "[ERROR] Build directory not found: $BDIR" >&2
  exit 1
fi

PY_BIND_DIR="$BDIR/bindings/python"
if [[ ! -d "$PY_BIND_DIR" ]]; then
  echo "[ERROR] Python bindings dir missing: $PY_BIND_DIR (Did you build with -DDSPACES_PYTHON_BINDINGS=ON?)" >&2
  exit 1
fi
if [[ ! -f "$BDIR/bin/dspaces_server" ]]; then
  echo "[ERROR] dspaces_server binary not found in $BDIR/bin. Build may have failed." >&2
  exit 1
fi

if ! command -v mpirun >/dev/null 2>&1; then
  echo "[ERROR] mpirun not found in PATH." >&2
  exit 1
fi

export PYTHONPATH="$PY_BIND_DIR:${PYTHONPATH:-}"
if [[ $USE_SHARED_LIBS -eq 1 ]]; then
  export LD_LIBRARY_PATH="$BDIR/lib:$LD_LIBRARY_PATH"
fi
if [[ $ENABLE_DEBUG -eq 1 ]]; then
  export DSPACES_DEBUG=1
fi

mkdir -p "$EX_DIR"
cd "$EX_DIR"

CONF_FILE="dataspaces.conf"
if [[ ! -f $CONF_FILE ]]; then
  cat > $CONF_FILE <<EOF
## Auto-generated by run_ex5_python.sh
ndim = 1
dims = $ARRAY_SIZE
max_versions = 10
num_apps = 2
EOF
  echo "[INFO] Created $CONF_FILE with dims=$ARRAY_SIZE num_apps=2"
fi

# Validate dims value matches ARRAY_SIZE
CONF_DIMS=$(grep -E '^\s*dims\s*=\s*' "$CONF_FILE" | sed -E 's/.*=\s*([0-9]+).*/\1/' || true)
if [[ "$CONF_DIMS" != "$ARRAY_SIZE" ]]; then
  echo "[WARN] dims ($CONF_DIMS) != ARRAY_SIZE ($ARRAY_SIZE). Update $CONF_FILE or use -a to match." >&2
fi

# Simple divisibility check for writer/reader
if (( ARRAY_SIZE % WRITER_RANKS != 0 )); then
  echo "[ERROR] ARRAY_SIZE $ARRAY_SIZE not divisible by writer ranks $WRITER_RANKS" >&2
  exit 1
fi
if (( ARRAY_SIZE % READER_RANKS != 0 )); then
  echo "[ERROR] ARRAY_SIZE $ARRAY_SIZE not divisible by reader ranks $READER_RANKS" >&2
  exit 1
fi

timestamp() { date '+%Y-%m-%d %H:%M:%S'; }

LOG_SERVER=server.log
LOG_WRITER=writer.log
LOG_READER=reader.log
rm -f $LOG_SERVER $LOG_WRITER $LOG_READER

echo "[INFO] Launching server: mpirun -n $SERVER_RANKS $BDIR/bin/dspaces_server $TRANSPORT"
mpirun -n "$SERVER_RANKS" "$BDIR/bin/dspaces_server" "$TRANSPORT" > "$LOG_SERVER" 2>&1 &
SERVER_PID=$!

echo "[INFO] Waiting for conf.ds ..."
for i in {1..40}; do
  if [[ -f conf.ds ]]; then
    echo "[INFO] conf.ds detected"
    break
  fi
  sleep 0.25
  if ! kill -0 $SERVER_PID 2>/dev/null; then
    echo "[ERROR] Server process died early. See $LOG_SERVER" >&2
    exit 1
  fi
  if [[ $i -eq 40 ]]; then
    echo "[ERROR] Timeout waiting for conf.ds" >&2
    exit 1
  fi
done

cleanup() {
  echo "\n[INFO] Caught signal, terminating background jobs..."
  [[ -n ${WRITER_PID:-} ]] && kill $WRITER_PID 2>/dev/null || true
  [[ -n ${READER_PID:-} ]] && kill $READER_PID 2>/dev/null || true
  kill $SERVER_PID 2>/dev/null || true
  wait || true
  echo "[INFO] Cleanup complete. Logs: $LOG_SERVER $LOG_WRITER $LOG_READER"
}
trap cleanup INT TERM

echo "[INFO] Launching writer: mpirun -n $WRITER_RANKS python minmaxavg_writer.py $ARRAY_SIZE"
mpirun -n "$WRITER_RANKS" python minmaxavg_writer.py "$ARRAY_SIZE" > "$LOG_WRITER" 2>&1 &
WRITER_PID=$!
sleep 0.5

echo "[INFO] Launching reader: mpirun -n $READER_RANKS python minmaxavg_reader.py $ARRAY_SIZE"
mpirun -n "$READER_RANKS" python minmaxavg_reader.py "$ARRAY_SIZE" > "$LOG_READER" 2>&1 &
READER_PID=$!

if [[ $NO_TAIL -eq 0 ]]; then
  echo "[INFO] All components launched. Tailing logs (Ctrl-C to stop)."
  echo "[INFO] --- server.log / writer.log / reader.log ---"
  echo
  # Tail combined view with prefixes
  tail -n0 -F "$LOG_SERVER" "$LOG_WRITER" "$LOG_READER" | awk '
    BEGIN{ while((getline)<0); }
    FILENAME!=last { last=FILENAME }
    { printf("[%s] (%s) %s\n", strftime("%H:%M:%S"), FILENAME, $0); fflush(); }
  '
fi

wait $WRITER_PID || true
wait $READER_PID || true
wait $SERVER_PID || true

SERVER_RC=$?
WRITER_RC=0
READER_RC=0
echo "[INFO] Finished. Exit codes: server($SERVER_RC), writer($WRITER_RC), reader($READER_RC)." 
if [[ $NO_TAIL -eq 1 ]]; then
  echo "[INFO] --- server.log (tail) ---"; tail -n 40 "$LOG_SERVER" || true
  echo "[INFO] --- writer.log (tail) ---"; tail -n 40 "$LOG_WRITER" || true
  echo "[INFO] --- reader.log (tail) ---"; tail -n 40 "$LOG_READER" || true
fi
echo "[INFO] Logs retained: $EX_DIR/$LOG_SERVER $EX_DIR/$LOG_WRITER $EX_DIR/$LOG_READER"
